"""Add rank column to finder_query_documents

Revision ID: 0dd37236c766
Revises: 2244e70e2f8b
Create Date: 2024-08-17 17:58:43.299418

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd37236c766"
down_revision: str | None = "2244e70e2f8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("finder_query_documents", sa.Column("rank", sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("finder_query_documents", "rank")
    # ### end Alembic commands ###
