version: '3.8'

services:
  finder:
    container_name: finder
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: similar_design_finder_service:latest
    command: uvicorn src.app.app:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./.model_cache:/app/.model_cache
