version: '3.8'

services:
  finder:
    container_name: finder
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: similar_design_finder_service:latest
    platform: linux/amd64
    environment:
      - ENV=${ENV}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
      - API_VERSION_STR=${API_VERSION_STR}
    ports:
      - 8080:8080
    volumes:
      - model_cache:/app/.model_cache
    networks:
      - mlsd_network

volumes:
  model_cache:
    external: true

networks:
  mlsd_network:
    external: true
