name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - develop/CICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Starting deployment..."
          echo "Stopping existing Docker container if it exists..."
          docker stop ghcr.io/simulatorml/similar-design-finder:latest
          docker rm ghcr.io/simulatorml/similar-design-finder:latest
          echo "Pulling Docker image..."
          docker pull ghcr.io/simulatorml/similar-design-finder:latest
          echo "Running new Docker container..."
          docker run -d --name similar-design-finder ghcr.io/simulatorml/similar-design-finder:latest
          docker logout ghcr.io
