name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop/CICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker --version
            echo "Pulling Docker image..."
            docker pull ghcr.io/simulatorml/similar-design-finder:latest
            echo "Stopping existing Docker container if it exists..."
            docker stop similar-design-finder || true
            docker rm similar-design-finder || true
            echo "Running new Docker container..."
            docker run -d --name similar-design-finder ghcr.io/simulatorml/similar-design-finder:latest
          EOF

