name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - develop/CICD
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --only dev

      - name: Run linters and formatters
        id: lint
        run: poetry run ruff check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u simulatorml --password-stdin

      - name: Create .env.prod file from secrets
        run: echo "${{ secrets.ENV_PROD }}" > .env.prod

      - name: Build Docker image
        run: docker-compose -f docker/docker-compose.yaml build

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/simulatorml/similar-design-finder:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Logging in to GitHub Container Registry..."
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Starting deployment..."
            echo "Stopping existing Docker containers if they exist..."
            docker stop finder || true
            docker rm finder || true
            echo "Pulling Docker image..."
            docker pull ghcr.io/simulatorml/similar-design-finder:latest
            echo "Creating .env.prod file..."
            echo "${{ secrets.ENV_PROD }}" > .env.prod
            echo "Running new Docker container..."
            docker run --env-file .env.prod -d --name finder --network mlsd_network -p 8080:8080 ghcr.io/simulatorml/similar-design-finder:latest
