name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - develop/CICD
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u simulatorml --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/simulatorml/similar-design-finder:latest .
          docker push ghcr.io/simulatorml/similar-design-finder:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pre-commit pytest

      - name: Run linters
        id: lint
        run: pre-commit run --all-files
        continue-on-error: true

      - name: Commit changes made by linters
        if: steps.lint.outcome == 'failure'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply linters' fixes"
          git push

      - name: Run tests
        run: pytest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Logging in to GitHub Container Registry..."
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Starting deployment..."
            echo "Stopping existing Docker container if it exists..."
            docker ps -a --filter ancestor=ghcr.io/simulatorml/similar-design-finder:latest -q | xargs -r docker stop
            docker ps -a --filter ancestor=ghcr.io/simulatorml/similar-design-finder:latest -q | xargs -r docker rm
            echo "Pulling Docker image..."
            docker pull ghcr.io/simulatorml/similar-design-finder:latest
            echo "Running new Docker container..."
            docker run -d ghcr.io/simulatorml/similar-design-finder:latest
